xcodeproj 'recycleplus.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'recycleplus' do

end

target 'recycleplusTests' do

end

target 'recycleplusUITests' do

end

